blank_issues_enabled: false
contact_links:
  - name: ğŸ¤” Long question or idea
    url: https://github.com/kiliman/remix-params-helper/discussions
    about: Ask long-form questions and discuss ideas.
  - name: ğŸ’¬ Remix Discord Channel 
    url: https://rmx.as/discord
    about: Interact with other people using Remix ğŸ“€
  - name: ğŸ’¬ New Updates (Twitter)
    url: https://twitter.com/remix_run
    about: Stay up to date with Remix news on twitter
  - name: ğŸ¿ Remix YouTube Channel
    url: https://www.youtube.com/channel/UC_9cztXyAZCli9Cky6NWWwQ
    about: Are you a techlead or wanting to learn more about Remix in depth? Checkout the Remix YouTube Channel 
